# -*- coding: utf-8 -*-
"""webscrap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b7apvW9DU44EAExlXwhgmg7HabiblgWg
"""

import requests
from bs4 import BeautifulSoup
import csv

url="https://results.eci.gov.in/PcResultGenJune2024/index.htm"

page=requests.get(url)

soup=BeautifulSoup(page.content,'html.parser')

table = soup.find('table', class_ = 'table')

print(table)

#soup.find_all('table')
world_titles=soup.find_all('th')

print(world_titles)

world_table_titles = [title.text.strip() for title in world_titles]

print(world_table_titles)

world_table_titles = ['Party', 'Won', 'Leading', 'Total']





world_t = [title.text.strip() for title in t]

print(world_t)



import pandas as pd
df = pd.DataFrame(columns = world_table_titles)

df

world_t=['Party', 'Won', 'Leading', 'Total']

column_data = table.find_all('tr')

import pandas as pd

world_table_titles = ['Party', 'Won', 'Leading', 'Total']
df = pd.DataFrame(columns=world_table_titles)

# Assuming 'table' is a BeautifulSoup object representing the HTML table
column_data = table.find_all('tr')

for row in column_data[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]

    # Check if the number of elements matches the DataFrame columns
    if len(individual_row_data) == len(df.columns):
        length = len(df)
        df.loc[length] = individual_row_data
    else:
        print(f"Skipping row due to mismatch: {individual_row_data}")

df















